Adding support to integrationnet
StardustCollective/dag-explorer-v2 pull request #35
Opened 2023-07-05 20:29 UTC by IPadawans

### Changes
+ Adding support to the new network: IntegrationNet

### JIRA
[DEW-77](https://constellationnetwork.atlassian.net/browse/DEW-77)

### Notes
+ We don't have the official URLs yet
+ We are using the URLs of testnet while we don't have the official ones
+ We should remove the tmp file before merging

2023-07-07 15:26 UTC, juandavidkincaid requested changes
In general looks great, with a couple of pattern changes and style changes...

Were you able to configure the domains w/ Alex?

2023-07-07 15:26 UTC, juandavidkincaid commented on src/components/Footer/Footer.tsx
> +    window.open('https://www.google.com', '_blank');
*Note:* Pending change to typeform.

Ps. internal note for me to review later.

2023-07-07 15:26 UTC, juandavidkincaid commented on src/components/TransactionsTable/SkeletonTransactionsTable.tsx
> +          <div className={`${styles.skeleton} ${styles.value}`} />
Please use clsx, or cls, or classnames.

2023-07-07 15:26 UTC, juandavidkincaid commented on src/components/TransactionsTable/TransactionRow.tsx
> +          <div className={`${clsx( isLastRow ? styles.txnCellLastRow :  styles.txnCell)}`}>
Interpolation is not doing anything here.

2023-07-07 15:26 UTC, juandavidkincaid commented on src/components/TransactionsTable/TransactionRow.tsx
> +          <div className={clsx(clsx( isLastRow ? styles.txnCellLastRow :  styles.txnCell), styles.txnDirection)}>
Use just one clsx call.

2023-07-07 15:26 UTC, juandavidkincaid commented on .env
> +REACT_APP_INTEGRATIONNET_TWO_L0_NODE_URL=https://l0-lb-testnet.constellationnetwork.io
Isn't this file generated?, if so, can you please remove it?

2023-07-07 15:58 UTC, IPadawans commented on .env
> +REACT_APP_INTEGRATIONNET_TWO_L0_NODE_URL=https://l0-lb-testnet.constellationnetwork.io
Done

2023-07-10 18:23 UTC, juandavidkincaid approved these changes

2023-07-13 20:21 UTC, merged